POST http://localhost:3001/api/properties
Content-Type: application/json

{
  "name": "Property 2",
  "currency": "GBP",
  "date": "2022-01-01",
  "value": 2000,
  "TaxStatus": "Taxable",
  "type": "Property",

  "city": "London",
  "country": "United Kingdom",
  "address": "123 Main St",
  "zip": "123"
}
