name: Node CI

on: [push]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy to heroku
        run: |
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY_SANTI }}@git.heroku.com/inheritly-app.git
          git push heroku HEAD:main
  deploy-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY_SANTI }}
          heroku_app_name: "inheritly-app"
          heroku_email: "santiagospidrobo15@gmail.com"