name: Node CI

on: [push]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

          
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY_SANTI }}
          heroku_app_name: "inheritly-app"
          heroku_email: "santiagospidrobo15@gmail.com"

  deploy-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
          
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

          
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.6.8
      with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY_SANTI }}
          heroku_app_name: "inheritly-app"
          heroku_email: "santiagospidrobo15@gmail.com"